-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 18:59:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rssfeeds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rssfeeds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rssfeeds` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rssfeeds` ;

-- -----------------------------------------------------
-- Table `rssfeeds`.`app_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`app_config` (
  `idapp_config` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `update_at` TIMESTAMP(5) NOT NULL,
  `created_at` TIMESTAMP(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idapp_config`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rssfeeds`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`topics` (
  `idtopics` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP(5) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idtopics`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rssfeeds`.`feeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`feeds` (
  `idfeed` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `author` VARCHAR(45) NULL DEFAULT NULL,
  `topic` INT(11) NULL DEFAULT NULL,
  `link` VARCHAR(100) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP(5) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(5) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idfeed`),
  INDEX `feed_topics_fk_idx` (`topic` ASC) VISIBLE,
  CONSTRAINT `feed_topics_fk`
    FOREIGN KEY (`topic`)
    REFERENCES `rssfeeds`.`topics` (`idtopics`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rssfeeds`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rssfeeds`.`news_rss_sources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`news_rss_sources` (
  `idnews_rss_sources` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `topic` INT(11) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP(5) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idnews_rss_sources`),
  INDEX `news_topics_fk_idx` (`topic` ASC) VISIBLE,
  CONSTRAINT `news_topics_fk`
    FOREIGN KEY (`topic`)
    REFERENCES `rssfeeds`.`topics` (`idtopics`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rssfeeds`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`status` (
  `idstatus` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `updated_at` TIMESTAMP(5) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rssfeeds`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`users` (
  `email` VARCHAR(50) NOT NULL,
  `status` INT(11) NOT NULL,
  `updated_at` TIMESTAMP(5) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(5) NULL DEFAULT NULL,
  PRIMARY KEY (`email`),
  INDEX `status_id_fk_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `status_id_fk`
    FOREIGN KEY (`status`)
    REFERENCES `rssfeeds`.`status` (`idstatus`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rssfeeds`.`user__topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssfeeds`.`user__topics` (
  `iduser_topic` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` VARCHAR(50) NOT NULL,
  `idtopic` INT(11) NOT NULL,
  `updated_at` TIMESTAMP(5) NULL DEFAULT NULL,
  `created_at` TIMESTAMP(5) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser_topic`),
  INDEX `idusers_fk_idx` (`iduser` ASC) VISIBLE,
  INDEX `idtopics_fk_idx` (`idtopic` ASC) VISIBLE,
  CONSTRAINT `idtopics_fk`
    FOREIGN KEY (`idtopic`)
    REFERENCES `rssfeeds`.`topics` (`idtopics`),
  CONSTRAINT `iduser_fk`
    FOREIGN KEY (`iduser`)
    REFERENCES `rssfeeds`.`users` (`email`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
